# overall
title: fi3ework's resume

# page 1
name: Wee
nickname: fi3ework
introduce: å‰ç«¯å·¥ç¨‹å¸ˆ
social:
  github: //github.com/fi3ework 
  wechat: assets/wechat.JPG
  email: 805843200@qq.com
  juejin: //juejin.im/user/56417d1e00b0bf378b7297ea
  tele: 185xxxxoooo
pdf_name: '[WEIWEI_RESUME.pdf](assets/resume.pdf)'

# page 2
education:
  title: æ•™è‚²èƒŒæ™¯
  stages:
    - 
      time: 2014.09 - 2017.03
      university: åŒ—äº¬ç†å·¥å¤§å­¦
      major: ä»ªå™¨ç§‘å­¦ä¸æŠ€æœ¯
    - 
      time: 2010.09 - 2014.06
      university: åŒ—äº¬ç†å·¥å¤§å­¦
      major: æµ‹æ§æŠ€æœ¯ä¸ä»ªå™¨

# page 3
work_experience:
  title: å·¥ä½œç»å†
  stages: 
    - 
      company: ğŸ˜¶ğŸ˜ğŸ˜‘å…¬å¸
      job_title: å›¾åƒç®—æ³•å·¥ç¨‹å¸ˆ
      time: 2017.3 - è‡³ä»Š
      tech_stack:
        - C++
        - OpenCV
      description:
        - å†™BUG
        - ä¿®BUG

# page 4
open_source:
  title: å¼€æºä½œå“
  works:
    - 
      name: hexo-theme-archer
      abstract: ä¸€æ¬¾ç®€æ´ç²¾è‡´çš„ hexo ä¸»é¢˜
      link: https://github.com/fi3ework/hexo-theme-archer
      tech_stack: gulp sass 
      description: 
        - Lorem ipsum dolor sit amet, offendit referrentur ad vix, his id lucilius partiendo. 
        - In populo aperiri eum, eam te suas consul scaevola, eam ut mollis partiendo definitionem. 
    - 
      name: douban-movie-react
      abstract: åŸºäº React çš„è¶…é«˜ä»¿è±†ç“£ç”µå½±
      link: https://github.com/fi3ework/douban-movie-react
      tech_stack: react redux react-router antd
      description: 
        - Pro accumsan oportere eu, dicta eruditi dissentiet eu quo. Pri id postea aperiri eloquentiam. 
        - Quem salutatus an ius, id erat aliquid per. Ullum copiosae comprehensam ne pri, id libris alienum pro.

# page 5
tech_stack:
  title: ä¸“ä¸šæŠ€èƒ½
  techs:
    - HTML5
    - CSS3
    - ES5/6
    - Gulp
    - Git
    - å‰ç«¯å·¥ç¨‹åŒ–
    - æ€§èƒ½ä¼˜åŒ–

# page 6
farewell: May the force be with you.
